<?php
define("MMS_COMMENTS_MODULE_ID", "mms.comments");
define("MMS_COMMENTS_IBLOCK_TYPE_CODE", "mms_comments");
define("MMS_COMMENTS_IBLOCK_CODE", "comments");
define("MMS_COMMENTS_PROPERTY_OBJECT_TYPE_CODE", "COMMENT_OBJECT_TYPE");
define("MMS_COMMENTS_PROPERTY_OBJECT_CODE", "COMMENT_OBJECT");
define("MMS_COMMENTS_PROPERTY_PARENT_CODE", "PARENT_COMMENT");
define("MMS_COMMENTS_PROPERTIES_IN_IBLOCK_TABLE", 2);
define("MMS_COMMENTS_PROPERTY_OBJECT_TYPE_ELEMENT", "TYPE_ELEMENT");
define("MMS_COMMENTS_PROPERTY_OBJECT_TYPE_PAGE", "TYPE_PAGE");
